import turtle

hank = turtle.Turtle()
scn = turtle.Screen()
bill = turtle.Turtle()
dale = turtle.Turtle()
boomhauer = turtle.Turtle()

hank.shape("turtle")
bill.shape("square")
dale.shape("circle")

hank.fillcolor("yellow green")
hank.begin_fill()
hank.circle(200)
hank.end_fill()

bill.goto(-80, 240)
bill.circle(20)
bill.fillcolor("white")
bill.begin_fill()
bill.circle(20)
bill.end_fill()

bill.penup()

bill.goto(80, 240)
bill.circle(20)
bill.fillcolor("white")
bill.begin_fill()
bill.circle(20)
bill.end_fill()

bill.penup()

bill.goto(80, 250)
bill.fillcolor("black")
bill.begin_fill()
bill.circle(10)
bill.end_fill()

bill.goto(-80, 250)
bill.fillcolor("black")
bill.begin_fill()
bill.circle(10)
bill.end_fill()

hank.penup()
hank.goto(-150, 150)
hank.pensize(10)
hank.pendown()
hank.forward(270)
hank.right(135)

bill.penup()
bill.goto(0, -100)

hank.penup()
hank.goto(0, -200)

dale.penup()
dale.goto(160, 320)
dale.pendown()
dale.left(45)
dale.pensize(3)
dale.forward(100)
dale.penup()
dale.right(90)
dale.forward(7)
dale.left(90)
dale.forward(5)
dale.left(90)
dale.forward(3)
dale.begin_fill()
dale.circle(10)
dale.end_fill()

dale.penup()
dale.goto(-160, 320)
dale.pendown()
dale.pensize(3)
dale.forward(100)
dale.right(90)
dale.forward(2)
dale.left(90)
dale.forward(3)
dale.begin_fill()
dale.circle(10)
dale.end_fill()

dale.penup()
dale.goto(0, -300)

boomhauer.penup()
boomhauer.goto(200, -50)
boomhauer.pendown()
boomhauer.pensize(5)
boomhauer.color("green")
boomhauer.write("Shrek Emoji")
turtle.exitonclick()